services:
  - type: web
    name: vinyl-collection-manager
    runtime: python
    buildCommand: pip install -r requirements.txt && cd frontend && npm install && npm run build && cd ..
    startCommand: cd /opt/render/project/src && gunicorn 'barcode_scanner.server:app' --bind=0.0.0.0:$PORT --log-file=-
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: DISCOGS_TOKEN
        sync: false

databases:
  - name: vinyl-collection-db
    databaseName: vinyl_collection
    ipAllowList: []
