services:
  - type: web
    name: vinyl-collection-manager
    runtime: python
    buildCommand: pip install -r requirements.txt && cd frontend && npm install && npm run build
    startCommand: gunicorn barcode_scanner.server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: DISCOGS_TOKEN
        sync: false

databases:
  - name: vinyl-collection-db
    databaseName: vinyl_collection
    ipAllowList: []
